name: Build Kernel
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@main
    with:
      release: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/maint-6.6"]'), github.ref) }}
      runs-on-amd64: ubuntu-latest-64core
      runs-on-arm64: ubuntu-latest-arm-64core
